from std.testing import assert_equal, assert_raises

from exec_parser import empty_exec_plan, parse_exec_file, parse_exec_line, require_standalone_setup_only


def main() raises:
    var plan = parse_exec_file("reference/trip4d_p101_cpu_20260511_140457/P101_iGTV_3Dplan.exec")

    assert_equal(len(plan.includes), 1)
    assert_equal(plan.includes[0], "/home/max/Projects/TRIP_DATA/Basedata/initGSI_12C_bio.exec")
    assert_equal(plan.scancap_bolus_mm_h2o, 40.0)
    assert_equal(plan.scancap_off_h2o_mm, 1.709)
    assert_equal(plan.scancap_x_limit_mm, 90.0)
    assert_equal(plan.scancap_y_limit_mm, 90.0)
    assert_equal(plan.scancap_scanner_x_mm, 8832.0)
    assert_equal(plan.scancap_scanner_y_mm, 7806.0)
    assert_equal(plan.scancap_min_particles, 5000.0)
    assert_equal(plan.scancap_couch_degrees, 0.0)
    assert_equal(plan.scancap_gantry_degrees, -2.203)
    assert_equal(plan.scancap_rifi_index, 3)
    assert_equal(plan.hlut_path, "/home/max/Projects/TRIP_DATA/Basedata/GSI/19990211.hlut")
    assert_equal(plan.ddd_path_pattern, "/home/max/Projects/TRIP_DATA/Basedata/GSI/carbon/DDD/*ddd")
    assert_equal(plan.spc_path_pattern, "/home/max/Projects/TRIP_DATA/Basedata/GSI/carbon/SPC/*spc")
    assert_equal(plan.dedx_path, "/home/max/Projects/TRIP_DATA/Basedata/GSI/carbon/20040607.dedx")
    assert_equal(len(plan.rbe_tables), 2)
    assert_equal(plan.rbe_tables[0].name, "chordom02")
    assert_equal(plan.rbe_tables[1].name, "hirn02")
    assert_equal(plan.ct_base_path, "/home/max/Projects/TRIP_DATA/P101/CT/P101_00")
    assert_equal(plan.voi_base_path, "/home/max/Projects/TRIP_DATA/P101/VOI/3D/P101")
    assert_equal(plan.voi_read_selection, "*")
    assert_equal(plan.voi_commands[0].action, "targetset")
    assert_equal(plan.voi_commands[0].use, True)
    assert_equal(plan.voi_commands[0].bin_state, "INTRSC")
    assert_equal(plan.voi_commands[1].argument0, 5.0)
    assert_equal(plan.voi_commands[1].argument1, 10.0)
    assert_equal(plan.prescription_dose_gy, 3.0)
    assert_equal(plan.target_tissue, "chordom02")
    assert_equal(plan.residual_tissue, "hirn02")

    assert_equal(len(plan.fields), 2)
    assert_equal(plan.fields[0].number, 1)
    assert_equal(plan.fields[0].gantry_degrees, 280.0)
    assert_equal(plan.fields[0].couch_degrees, 90.0)
    assert_equal(plan.fields[0].raster_x_mm, 2.0)
    assert_equal(plan.fields[0].raster_y_mm, 2.0)
    assert_equal(plan.fields[0].contour_extension, 1.2)
    assert_equal(plan.fields[0].z_step_mm, 3.0)
    assert_equal(plan.fields[0].distal_extension_mm, 3.0)
    assert_equal(plan.fields[0].robust_range_mm_h2o, 3.5)
    assert_equal(plan.fields[0].robust_position_mm, 3.0)
    assert_equal(plan.fields[0].target_voi, "Tumor")
    assert_equal(plan.fields[0].write_rst_path, "/home/max/Projects/trip-mojo/reference/trip4d_p101_cpu_20260511_140457/StaticP101_2110_field1_iGTV_R.rst")

    assert_equal(plan.fields[1].number, 2)
    assert_equal(plan.fields[1].gantry_degrees, 325.0)
    assert_equal(plan.fields[1].write_rst_path, "/home/max/Projects/trip-mojo/reference/trip4d_p101_cpu_20260511_140457/StaticP101_2110_field2_iGTV_R.rst")

    assert_equal(plan.has_optimization, True)
    assert_equal(plan.optimization.biological, True)
    assert_equal(plan.optimization.bioalg, "ld")
    assert_equal(plan.optimization.optalg, "fdcb")
    assert_equal(plan.optimization.dosealg, "msdb")
    assert_equal(plan.optimization.iterations, 300)
    assert_equal(plan.optimization.max_threads, 40)
    assert_equal(plan.optimization.no_preopt, True)
    assert_equal(plan.optimization.no_dose_weight, True)
    assert_equal(plan.optimization.selected_fields, "*")
    assert_equal(plan.optimization.ct_based, True)
    assert_equal(plan.optimization.maximum_dose_weight, 1.0)

    assert_equal(plan.has_dose_calc, True)
    assert_equal(plan.dose_calc.output_base, "/home/max/Projects/trip-mojo/reference/trip4d_p101_cpu_20260511_140457/3Ddose_P101_2110_iGTV")
    assert_equal(plan.dose_calc.algorithm, "msdb")
    assert_equal(plan.dose_calc.biological, True)
    assert_equal(plan.dose_calc.bioalg, "ld")
    assert_equal(plan.dose_calc.write, True)
    assert_equal(plan.dose_calc.datatype, "float")
    assert_equal(plan.dose_calc.direct, True)
    assert_equal(plan.dose_calc.voi, "Body")
    assert_equal(plan.dose_calc.no_svv, True)
    assert_equal(plan.dose_calc.no_rbe, True)
    assert_equal(plan.has_dvh, True)
    assert_equal(plan.dvh.biological, True)
    assert_equal(plan.dvh.exchange_format, "gd")
    assert_equal(plan.dvh.write, True)
    assert_equal(plan.quit_requested, True)

    with assert_raises():
        require_standalone_setup_only(plan)

    var invalid = empty_exec_plan("invalid.exec")
    with assert_raises():
        parse_exec_line(invalid, "opt / bio silentlyignored(1)", False)
    with assert_raises():
        parse_exec_line(invalid, "dose \"x\" / calc mysteryflag", False)
